### ISSUE TITLE
tf_nndistance_so.so

### ISSUE THREAD

**Issue by sunbo666** [vinits5/pc_autoencoder#1]
hello
i tried to run the train code but it showed:

python pointnet_autoencoder_train.py 
Traceback (most recent call last):
  File "pointnet_autoencoder_train.py", line 79, in <module>
    MODEL = importlib.import_module(FLAGS.model) # import network module
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/sun/pc_autoencoder/models/pointnet_pose.py", line 12, in <module>
    import tf_util_loss
  File "/home/sun/pc_autoencoder/utils/tf_util_loss.py", line 2, in <module>
    from pc_distance import tf_nndistance, tf_approxmatch
  File "/home/sun/pc_autoencoder/utils/pc_distance/tf_nndistance.py", line 5, in <module>
    nn_distance_module=tf.load_op_library(os.path.join(BASE_DIR, 'tf_nndistance_so.so'))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /home/sun/pc_autoencoder/utils/pc_distance/tf_nndistance_so.so: cannot open shared object file: No such file or directory

and i tried to use "makefile" in "pc_distance",it showed:

make: 放弃循环依赖 tf_nndistance.cu <- tf_nndistance.cu.o 。
g++ tf_nndistance.cpp tf_nndistance.cu.o -o tf_nndistance_so.so \
-I /usr/local/cuda-8.0/include/ -I /usr/local/lib/python2.7/dist-packages/tensorflow/include -I /usr/local/lib/python2.7/dist-packages/external/nsync/public \
-L /usr/local/cuda-8.0/lib64/ -lcudart \
-L /usr/local/lib/python2.7/dist-packages/tensorflow/core/lib  -ltensorflowframe\
    -shared -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -fPIC -O2
/usr/bin/ld: 找不到 -ltensorflow
collect2: error: ld returned 1 exit status
makefile:15: recipe for target 'tf_nndistance_so.so' failed
make: *** [tf_nndistance_so.so] Error 1

is it because our environment is different?or something else

**Comment by sohee-zoe** [comment]
Modify **utils/pc_distance/makefile**

refer to the link below
[https://github.com/optas/latent_3d_points/issues/21#issuecomment-499279950](url)


in my case,
Ubuntu 16.04
tensorflow 1.13.1
cuda 10.0


```
import tensorflow as tf
from __future__ import print_function
print(tf.sysconfig.get_compile_flags(),'\n')
print(tf.sysconfig.get_link_flags())

```

output

```
['-I/home/**username**/anaconda3/envs/**py36**/lib/python3.6/site-packages/tensorflow/include', '-D_GLIBCXX_USE_CXX11_ABI=0'] 

['-L/home/**username**/anaconda3/envs/**py36**/lib/python3.6/site-packages/tensorflow', '-ltensorflow_framework']

```


**makefile**
```
cuda_inc = /usr/local/cuda-10.0/include/
cuda_lib = /usr/local/cuda-10.0/lib64/
nsync = /home/**username**/anaconda3/envs/**py36**/lib/python3.6/site-packages/tensorflow/include/external/nsync/public
nvcc = /usr/local/cuda-10.0/bin/nvcc
tf_inc = /home/**username**/anaconda3/envs/**py36**/lib/python3.6/site-packages/tensorflow/include
tf_lib = /home/**username**/anaconda3/envs/**py36**/site-packages/tensorflow

all: tf_nndistance_so.so tf_approxmatch_so.so

tf_nndistance.cu.o: tf_nndistance.cu
	$(nvcc) tf_nndistance.cu -o tf_nndistance.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC

tf_nndistance_so.so: tf_nndistance.cpp tf_nndistance.cu.o
	g++ tf_nndistance.cpp tf_nndistance.cu.o -o tf_nndistance_so.so \
	-I $(cuda_inc) -I $(tf_inc) -I $(nsync) \
	-L $(cuda_lib) -lcudart -L $(tf_lib) -ltensorflow_framework \
    -shared -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -fPIC -O2

tf_approxmatch.cu.o: tf_approxmatch.cu
	$(nvcc) tf_approxmatch.cu -o tf_approxmatch.cu.o -c -O2 -DGOOGLE_CUDA=1 -x cu -Xcompiler -fPIC

tf_approxmatch_so.so: tf_approxmatch.cpp tf_approxmatch.cu.o
	g++ -shared $(CPPFLAGS) tf_approxmatch.cpp tf_approxmatch.cu.o -o tf_approxmatch_so.so \
	-I $(cuda_inc) -I $(tf_inc) -I $(nsync) \
	-L $(cuda_lib) -lcudart -L $(tf_lib) -ltensorflow_framework \
    -shared -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -fPIC -O2

clean:
	rm -rf *.o *.so

```
